### ISSUE TITLE
Wand disappears in arcane crafting table

### ISSUE THREAD

**Issue by Sixdd6** [Zoko061602/Thaumic-Wands#24]
I know this was reported before but it still seems to be a problem in 1.2.5.

Made an iron-capped wand, charged the wand with vis orbs, placed wand in arcane crafting table (in the wand slot), tried to remove wand and it disappeared. The wand also disappears if you just exit the arcane crafting table interface.

Mod Version: 1.2.5

[latest.log](https://github.com/Zoko061602/Thaumic-Wands/files/5081080/latest.log)
[debug.log](https://github.com/Zoko061602/Thaumic-Wands/files/5081081/debug.log)

EDIT: The following error also shows up in the server console:

```
[12:09:18] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 15
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 15
	at java.util.Arrays$ArrayList.set(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.NonNullList.set(SourceFile:51) ~[fi.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:92) ~[afy.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by xemnes** [comment]
im having the same problem.
